let output = document.querySelector('#output');

const hits = [
  {
    created_at: '2018-03-14T03:50:30.000Z',
    title: 'Stephen Hawking has died',
    url: 'http://www.bbc.com/news/uk-43396008',
    author: 'Cogito',
    points: 6015,
    story_text: null,
    comment_text: null,
    num_comments: 436,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1520999430,
    relevancy_score: 8012,
    _tags: ['story', 'author_Cogito', 'story_16582136'],
    objectID: '16582136',
    _highlightResult: {
      title: {
        value: 'Stephen Hawking has died',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value: 'http://www.bbc.com/news/uk-43396008',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: {
        value: 'Cogito',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    created_at: '2016-02-17T08:38:37.000Z',
    title: 'A Message to Our Customers',
    url: 'http://www.apple.com/customer-letter/',
    author: 'epaga',
    points: 5771,
    story_text: null,
    comment_text: null,
    num_comments: 967,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1455698317,
    relevancy_score: 6561,
    _tags: ['story', 'author_epaga', 'story_11116274'],
    objectID: '11116274',
    _highlightResult: {
      title: {
        value: 'A Message to Our Customers',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value: 'http://www.apple.com/customer-letter/',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: {
        value: 'epaga',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    created_at: '2011-10-05T23:42:23.000Z',
    title: 'Steve Jobs has passed away.',
    url: 'http://www.apple.com/stevejobs/',
    author: 'patricktomas',
    points: 4271,
    story_text: '',
    comment_text: null,
    num_comments: 376,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1317858143,
    relevancy_score: 3496,
    _tags: ['story', 'author_patricktomas', 'story_3078128'],
    objectID: '3078128',
    _highlightResult: {
      title: {
        value: 'Steve Jobs has passed away.',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value: 'http://www.apple.com/stevejobs/',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: {
        value: 'patricktomas',
        matchLevel: 'none',
        matchedWords: [],
      },
      story_text: {
        value: '',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    created_at: '2020-10-23T19:26:35.000Z',
    title: 'YouTube-dl has received a DMCA takedown from RIAA',
    url: 'https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md',
    author: 'phantop',
    points: 4240,
    story_text: null,
    comment_text: null,
    num_comments: 1411,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1603481195,
    _tags: ['story', 'author_phantop', 'story_24872911'],
    objectID: '24872911',
    _highlightResult: {
      title: {
        value: 'YouTube-dl has received a DMCA takedown from RIAA',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value:
          'https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: {
        value: 'phantop',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    created_at: '2017-02-19T21:16:33.000Z',
    title: 'Reflecting on one very, very strange year at Uber',
    url: 'https://www.susanjfowler.com/blog/2017/2/19/reflecting-on-one-very-strange-year-at-uber',
    author: 'grey-area',
    points: 4107,
    story_text: null,
    comment_text: null,
    num_comments: 1014,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1487538993,
    relevancy_score: 7260,
    _tags: ['story', 'author_grey-area', 'story_13682022'],
    objectID: '13682022',
    _highlightResult: {
      title: {
        value: 'Reflecting on one very, very strange year at Uber',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value:
          'https://www.susanjfowler.com/blog/2017/2/19/reflecting-on-one-very-strange-year-at-uber',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: {
        value: 'grey-area',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    created_at: '2021-04-05T14:04:22.000Z',
    title: 'Google’s copying of the Java SE API was fair use [pdf]',
    url: 'https://www.supremecourt.gov/opinions/20pdf/18-956_d18f.pdf',
    author: 'pdoconnell',
    points: 4103,
    story_text: null,
    comment_text: null,
    num_comments: 930,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1617631462,
    _tags: ['story', 'author_pdoconnell', 'story_26699106'],
    objectID: '26699106',
    _highlightResult: {
      title: {
        value: 'Google’s copying of the Java SE API was fair use [pdf]',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value: 'https://www.supremecourt.gov/opinions/20pdf/18-956_d18f.pdf',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: {
        value: 'pdoconnell',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    created_at: '2021-06-07T16:08:04.000Z',
    title: 'Replit used legal threats to kill my open-source project',
    url: 'https://intuitiveexplanations.com/tech/replit/',
    author: 'raxod502',
    points: 4022,
    story_text: null,
    comment_text: null,
    num_comments: 1274,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1623082084,
    _tags: ['story', 'author_raxod502', 'story_27424195'],
    objectID: '27424195',
    _highlightResult: {
      title: {
        value: 'Replit used legal threats to kill my open-source project',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value: 'https://intuitiveexplanations.com/tech/replit/',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: {
        value: 'raxod502',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    created_at: '2021-02-28T19:38:26.000Z',
    title: 'How I cut GTA Online loading times by 70%',
    url: 'https://nee.lv/2021/02/28/How-I-cut-GTA-Online-loading-times-by-70/',
    author: 'kuroguro',
    points: 3883,
    story_text: null,
    comment_text: null,
    num_comments: 697,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1614541106,
    _tags: ['story', 'author_kuroguro', 'story_26296339'],
    objectID: '26296339',
    _highlightResult: {
      title: {
        value: 'How I cut GTA Online loading times by 70%',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value:
          'https://nee.lv/2021/02/28/How-I-cut-GTA-Online-loading-times-by-70/',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: {
        value: 'kuroguro',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    created_at: '2020-05-04T08:43:35.000Z',
    title: 'Bye, Amazon',
    url: 'https://www.tbray.org/ongoing/When/202x/2020/04/29/Leaving-Amazon',
    author: 'grey-area',
    points: 3816,
    story_text: null,
    comment_text: null,
    num_comments: 1097,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1588581815,
    _tags: ['story', 'author_grey-area', 'story_23065782'],
    objectID: '23065782',
    _highlightResult: {
      title: {
        value: 'Bye, Amazon',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value:
          'https://www.tbray.org/ongoing/When/202x/2020/04/29/Leaving-Amazon',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: {
        value: 'grey-area',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    created_at: '2020-01-21T15:38:22.000Z',
    title: 'Every Google result now looks like an ad',
    url: 'https://twitter.com/craigmod/status/1219644556003565568',
    author: 'cmod',
    points: 3592,
    story_text: null,
    comment_text: null,
    num_comments: 969,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1579621102,
    _tags: ['story', 'author_cmod', 'story_22107823'],
    objectID: '22107823',
    _highlightResult: {
      title: {
        value: 'Every Google result now looks like an ad',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value: 'https://twitter.com/craigmod/status/1219644556003565568',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: {
        value: 'cmod',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    created_at: '2021-09-16T12:16:14.000Z',
    title:
      'A search engine that favors text-heavy sites and punishes modern web design',
    url: 'https://search.marginalia.nu/',
    author: 'Funes-',
    points: 3441,
    story_text: null,
    comment_text: null,
    num_comments: 717,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1631794574,
    _tags: ['story', 'author_Funes-', 'story_28550764'],
    objectID: '28550764',
    _highlightResult: {
      title: {
        value:
          'A search engine that favors text-heavy sites and punishes modern web design',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value: 'https://search.marginalia.nu/',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: {
        value: 'Funes-',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    created_at: '2022-01-07T21:41:56.000Z',
    title: 'My First Impressions of Web3',
    url: 'https://moxie.org/2022/01/07/web3-first-impressions.html',
    author: 'natdempk',
    points: 3393,
    story_text: null,
    comment_text: null,
    num_comments: 1129,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1641591716,
    _tags: ['story', 'author_natdempk', 'story_29845208'],
    objectID: '29845208',
    _highlightResult: {
      title: {
        value: 'My First Impressions of Web3',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value: 'https://moxie.org/2022/01/07/web3-first-impressions.html',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: {
        value: 'natdempk',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    created_at: '2017-12-14T18:13:35.000Z',
    title: 'F.C.C. Repeals Net Neutrality Rules',
    url: 'https://www.nytimes.com/2017/12/14/technology/net-neutrality-repeal-vote.html',
    author: 'panny',
    points: 3384,
    story_text: null,
    comment_text: null,
    num_comments: 1397,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1513275215,
    relevancy_score: 7838,
    _tags: ['story', 'author_panny', 'story_15924794'],
    objectID: '15924794',
    _highlightResult: {
      title: {
        value: 'F.C.C. Repeals Net Neutrality Rules',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value:
          'https://www.nytimes.com/2017/12/14/technology/net-neutrality-repeal-vote.html',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: {
        value: 'panny',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    created_at: '2012-03-23T00:40:39.000Z',
    title: 'Show HN: This up votes itself',
    url: 'http://news.ycombinator.com/vote?for=3742902\u0026dir=up\u0026whence=%6e%65%77%65%73%74',
    author: 'olalonde',
    points: 3381,
    story_text: '',
    comment_text: null,
    num_comments: 83,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1332463239,
    relevancy_score: 3819,
    _tags: ['story', 'author_olalonde', 'story_3742902', 'show_hn'],
    objectID: '3742902',
    _highlightResult: {
      title: {
        value: 'Show HN: This up votes itself',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value:
          'http://news.ycombinator.com/vote?for=3742902\u0026dir=up\u0026whence=%6e%65%77%65%73%74',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: {
        value: 'olalonde',
        matchLevel: 'none',
        matchedWords: [],
      },
      story_text: {
        value: '',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    created_at: '2021-03-17T08:11:38.000Z',
    title: 'GitHub, fuck your name change',
    url: 'https://mooseyanon.medium.com/github-f-ck-your-name-change-de599033bbbe',
    author: 'leontrolski',
    points: 3353,
    story_text: null,
    comment_text: null,
    num_comments: 2010,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1615968698,
    _tags: ['story', 'author_leontrolski', 'story_26487854'],
    objectID: '26487854',
    _highlightResult: {
      title: {
        value: 'GitHub, fuck your name change',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value:
          'https://mooseyanon.medium.com/github-f-ck-your-name-change-de599033bbbe',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: {
        value: 'leontrolski',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    created_at: '2019-05-30T16:09:19.000Z',
    title: 'Switch from Chrome to Firefox',
    url: 'https://www.mozilla.org/en-US/firefox/switch/',
    author: 'WisNorCan',
    points: 3287,
    story_text: null,
    comment_text: null,
    num_comments: 981,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1559232559,
    relevancy_score: 8859,
    _tags: ['story', 'author_WisNorCan', 'story_20052623'],
    objectID: '20052623',
    _highlightResult: {
      title: {
        value: 'Switch from Chrome to Firefox',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value: 'https://www.mozilla.org/en-US/firefox/switch/',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: {
        value: 'WisNorCan',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    created_at: '2020-04-19T21:33:46.000Z',
    title: "Ask HN: I'm a software engineer going blind, how should I prepare?",
    url: null,
    author: 'zachrip',
    points: 3270,
    story_text:
      'I\u0026#x27;m a 24 y\u0026#x2F;o full stack engineer (I know some of you are rolling your eyes right now, just highlighting that I have experience on frontend apps as well as backend architecture). I\u0026#x27;ve been working professionally for ~7 years building mostly javascript projects but also some PHP. Two years ago I was diagnosed with a condition called \u0026quot;Usher\u0026#x27;s Syndrome\u0026quot; - characterized by hearing loss, balance issues, and progressive vision loss.\u003cp\u003eI know there are blind software engineers out there. My main questions are:\u003cp\u003e- Are there blind frontend engineers?\u003cp\u003e- What kinds of software engineering lend themselves to someone with limited vision? Backend only?\u003cp\u003e- Besides a screen reader, what are some of the best tools for building software with limited vision?\u003cp\u003e- Does your company employ blind engineers? How well does it work? What kind of engineer are they?\u003cp\u003eI\u0026#x27;m really trying to get ahead of this thing and prepare myself as my vision is degrading rather quickly. I\u0026#x27;m not sure what I can do if I can\u0026#x27;t do SE as I don\u0026#x27;t have any formal education in anything. I\u0026#x27;ve worked really hard to get to where I am and don\u0026#x27;t want it to go to waste.\u003cp\u003eThank you for any input, and stay safe out there!\u003cp\u003eEdit:\u003cp\u003eThank you all for your links, suggestions, and moral support, I really appreciate it. Since my diagnosis I\u0026#x27;ve slowly developed a crippling anxiety centered around a feeling that I need to figure out the rest of my life before it\u0026#x27;s too late. I know I shouldn\u0026#x27;t think this way but it is hard not to. I\u0026#x27;m very independent and I feel a pressure to \u0026quot;show up.\u0026quot; I will look into these opportunities mentioned and try to get in touch with some more members of the blind engineering community.',
    comment_text: null,
    num_comments: 473,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1587332026,
    _tags: ['story', 'author_zachrip', 'story_22918980', 'ask_hn'],
    objectID: '22918980',
    _highlightResult: {
      title: {
        value:
          "Ask HN: I'm a software engineer going blind, how should I prepare?",
        matchLevel: 'none',
        matchedWords: [],
      },
      author: {
        value: 'zachrip',
        matchLevel: 'none',
        matchedWords: [],
      },
      story_text: {
        value:
          "I'm a 24 y/o full stack engineer (I know some of you are rolling your eyes right now, just highlighting that I have experience on frontend apps as well as backend architecture). I've been working professionally for ~7 years building mostly javascript projects but also some PHP. Two years ago I was diagnosed with a condition called \u0026quot;Usher's Syndrome\u0026quot; - characterized by hearing loss, balance issues, and progressive vision loss.\u003cp\u003eI know there are blind software engineers out there. My main questions are:\u003cp\u003e- Are there blind frontend engineers?\u003cp\u003e- What kinds of software engineering lend themselves to someone with limited vision? Backend only?\u003cp\u003e- Besides a screen reader, what are some of the best tools for building software with limited vision?\u003cp\u003e- Does your company employ blind engineers? How well does it work? What kind of engineer are they?\u003cp\u003eI'm really trying to get ahead of this thing and prepare myself as my vision is degrading rather quickly. I'm not sure what I can do if I can't do SE as I don't have any formal education in anything. I've worked really hard to get to where I am and don't want it to go to waste.\u003cp\u003eThank you for any input, and stay safe out there!\u003cp\u003eEdit:\u003cp\u003eThank you all for your links, suggestions, and moral support, I really appreciate it. Since my diagnosis I've slowly developed a crippling anxiety centered around a feeling that I need to figure out the rest of my life before it's too late. I know I shouldn't think this way but it is hard not to. I'm very independent and I feel a pressure to \u0026quot;show up.\u0026quot; I will look into these opportunities mentioned and try to get in touch with some more members of the blind engineering community.",
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    created_at: '2017-02-23T23:05:08.000Z',
    title: 'Cloudflare Reverse Proxies Are Dumping Uninitialized Memory',
    url: 'https://bugs.chromium.org/p/project-zero/issues/detail?id=1139',
    author: 'tptacek',
    points: 3238,
    story_text: null,
    comment_text: null,
    num_comments: 992,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1487891108,
    relevancy_score: 7273,
    _tags: ['story', 'author_tptacek', 'story_13718752'],
    objectID: '13718752',
    _highlightResult: {
      title: {
        value: 'Cloudflare Reverse Proxies Are Dumping Uninitialized Memory',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value: 'https://bugs.chromium.org/p/project-zero/issues/detail?id=1139',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: {
        value: 'tptacek',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    created_at: '2021-11-17T07:22:16.000Z',
    title: '“Click to subscribe, call to cancel” is illegal, FTC says',
    url: 'https://www.niemanlab.org/2021/11/the-end-of-click-to-subscribe-call-to-cancel-one-of-the-news-industrys-favorite-retention-tactics-is-illegal-ftc-says/',
    author: 'spzx',
    points: 3192,
    story_text: null,
    comment_text: null,
    num_comments: 860,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1637133736,
    _tags: ['story', 'author_spzx', 'story_29250063'],
    objectID: '29250063',
    _highlightResult: {
      title: {
        value: '“Click to subscribe, call to cancel” is illegal, FTC says',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value:
          'https://www.niemanlab.org/2021/11/the-end-of-click-to-subscribe-call-to-cancel-one-of-the-news-industrys-favorite-retention-tactics-is-illegal-ftc-says/',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: {
        value: 'spzx',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    created_at: '2016-06-24T03:48:57.000Z',
    title: 'UK votes to leave EU',
    url: 'http://www.bbc.co.uk/news/uk-politics-36615028',
    author: 'dmmalam',
    points: 3125,
    story_text: null,
    comment_text: null,
    num_comments: 2531,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1466740137,
    relevancy_score: 6802,
    _tags: ['story', 'author_dmmalam', 'story_11966167'],
    objectID: '11966167',
    _highlightResult: {
      title: {
        value: 'UK votes to leave EU',
        matchLevel: 'none',
        matchedWords: [],
      },
      url: {
        value: 'http://www.bbc.co.uk/news/uk-politics-36615028',
        matchLevel: 'none',
        matchedWords: [],
      },
      author: {
        value: 'dmmalam',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
];

window.onload = function () {
  hits.map((item) => {
    let link = document.createElement('a');
    let Urlhost = new URL(item.url).hostname;
    link.href = 'https://news.ycombinator.com/from?site=' + Urlhost;

    let newDiv = document.createElement('div');
    newDiv.innerHTML = `<li><a href="${item.url}">${item.title}</a> <a href="${item.link}">(url)</a>
            </li><span style="font-size:9pt;">${item.points} points by ${item.author} ${item.created_at} | hide | ${item.num_comments} comments</span>`;

    output.appendChild(newDiv);
  });
};
